SetColumns(0);
SetSeed(20260903);
Q:=Rationals(); Qz<z>:=PolynomialRing(Q);
mp:=z^6-1424*z^4+892928*z^2-303038464;
L<e0>:=NumberField(mp);
Lopt,phi:=OptimizedRepresentation(L);
e:=phi(e0);
print "L_ORIG_POLY",DefiningPolynomial(L);
print "L_OPT_POLY",DefiningPolynomial(Lopt);
print "L_OPT_DISC",Discriminant(Lopt);
LX<X>:=PolynomialRing(Lopt);
zeta:=12*(1280-e^2)/(e^2-512);
eta:=-4*(zeta+64)/e;
aa:=(-4+eta)/2;
bb:=(zeta+e)/2;
H1:=X^2+aa*X+bb;
LT<t>:=PolynomialRing(Lopt);
G0:=(t^2+1)^2+aa*(t^2+1)*(t+1)+bb*(t+1)^2;
d1:=Evaluate(H1,Lopt!1);
G1:=G0/d1;
CQ:=HyperellipticCurve(G1);
P0:=CQ![Lopt!0,Lopt!1,Lopt!1];
EQ,mpEQ:=EllipticCurve(CQ,P0);
print "CURVE",EQ;
print "TORSION",Invariants(TorsionSubgroup(EQ));
lo,hi:=RankBounds(EQ : Effort:=6);
print "RANK_BOUNDS_E1",lo,hi;
ranks,gens,sha:=MordellWeilShaInformation(EQ : RankOnly:=true, Effort:=6, HeightBound:=100);
print "MWSHA_RANKS",ranks;
print "MWSHA_GENS",gens;
print "MWSHA_SHA",sha;
G,m,rank_proved,full_group:=MordellWeilGroup(EQ : Effort:=6, HeightBound:=100);
print "MW_GROUP",Invariants(G),rank_proved,full_group;
print "MW_IMAGES",[m(G.i):i in [1..Ngens(G)]];
print "COVER1_RANK_DONE";
