SetColumns(0);
SetSeed(20260903);
Q:=Rationals(); Qr<r>:=PolynomialRing(Q);
mp:=r^6-9*r^4+8*r^2-144;
L<a>:=NumberField(mp);
print "FIELD_POLY",DefiningPolynomial(L);
print "FIELD_DISC",Discriminant(L);
print "FIELD_SIGNATURE",Signature(L);
LX<X>:=PolynomialRing(L);
aa:=2*a-2;
bb:=2*a^2-2*a-8-24/a;
H1:=X^2+aa*X+bb;
H2:=X^2+(-2*a-2)*X+(2*a^2+2*a-8+24/a);
H:=X^4-4*X^3-12*X^2+128*X-64;
print "FACTOR_OK",H1*H2 eq H;
LT<t>:=PolynomialRing(L);
G0:=(t^2+1)^2+aa*(t^2+1)*(t+1)+bb*(t+1)^2;
d1:=Evaluate(H1,L!1);
G1:=G0/d1;
print "D1",d1;
print "G1",G1;
CQ:=HyperellipticCurve(G1);
P0:=CQ![L!0,L!1,L!1];
EQ,mpEQ:=EllipticCurve(CQ,P0);
print "CURVE",EQ;
print "TORSION",Invariants(TorsionSubgroup(EQ));
lo,hi:=RankBounds(EQ : Effort:=12);
print "RANK_BOUNDS_E1",lo,hi;
G,m,rank_proved,full_group:=MordellWeilGroup(EQ : Effort:=12, HeightBound:=100);
print "MW_GROUP",Invariants(G),rank_proved,full_group;
print "MW_IMAGES",[m(G.i):i in [1..Ngens(G)]];
print "COVER1_RANK_DONE";
