import FanoLowerBound.OrderedLineCore

/-!
# General open-convex three-sunflower line-core theorem

This module removes the ordering hypothesis from
`ordered_openConvexThreeSunflower_line_hitsCore`.  Coincident petal-hit points
already lie in the common core by pair completion.  If the three hit points
are distinct, scalar parameters on the common affine line have a unique
middle element; after the corresponding simultaneous permutation of sets and
points, the ordered theorem applies.
-/

namespace FanoLowerBound

open AffineMap Set

variable {E : Type*} [AddCommGroup E] [Module ℝ E]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E]

/-- Three pairwise distinct real numbers have one of the three possible strict
betweenness orders.  The disjuncts say, respectively, that the middle element
is the second, first, or third argument. -/
theorem real_three_distinct_one_strictly_between
    {a b c : ℝ} (hab : a ≠ b) (hac : a ≠ c) (hbc : b ≠ c) :
    Sbtw ℝ a b c ∨ Sbtw ℝ b a c ∨ Sbtw ℝ a c b := by
  rcases lt_or_gt_of_ne hab with hablt | hbalt
  · rcases lt_or_gt_of_ne hbc with hbclt | hcblt
    · exact Or.inl (Sbtw.of_lt_of_lt hablt hbclt)
    · rcases lt_or_gt_of_ne hac with haclt | hcalt
      · exact Or.inr (Or.inr (Sbtw.of_lt_of_lt haclt hcblt))
      · exact Or.inr (Or.inl (Sbtw.of_lt_of_lt hcalt hablt).symm)
  · rcases lt_or_gt_of_ne hac with haclt | hcalt
    · exact Or.inr (Or.inl (Sbtw.of_lt_of_lt hbalt haclt))
    · rcases lt_or_gt_of_ne hbc with hbclt | hcblt
      · exact Or.inr (Or.inr (Sbtw.of_lt_of_lt hbclt hcalt).symm)
      · exact Or.inl (Sbtw.of_lt_of_lt hcblt hbalt).symm

/-- Three pairwise distinct points lying on one affine line have a strict
middle point. -/
theorem three_distinct_points_on_line_one_strictly_between
    {p q x₁ x₂ x₃ : E}
    (hx₁line : x₁ ∈ line[ℝ, p, q])
    (hx₂line : x₂ ∈ line[ℝ, p, q])
    (hx₃line : x₃ ∈ line[ℝ, p, q])
    (hx₁₂ : x₁ ≠ x₂) (hx₁₃ : x₁ ≠ x₃) (hx₂₃ : x₂ ≠ x₃) :
    Sbtw ℝ x₁ x₂ x₃ ∨ Sbtw ℝ x₂ x₁ x₃ ∨ Sbtw ℝ x₁ x₃ x₂ := by
  rw [mem_affineSpan_pair_iff_exists_lineMap_eq] at hx₁line hx₂line hx₃line
  rcases hx₁line with ⟨a, rfl⟩
  rcases hx₂line with ⟨b, rfl⟩
  rcases hx₃line with ⟨c, rfl⟩
  have hab : a ≠ b := by
    intro h
    apply hx₁₂
    rw [h]
  have hac : a ≠ c := by
    intro h
    apply hx₁₃
    rw [h]
  have hbc : b ≠ c := by
    intro h
    apply hx₂₃
    rw [h]
  rcases real_three_distinct_one_strictly_between hab hac hbc with hmid₂ | hmid₁ | hmid₃
  · exact Or.inl ⟨hmid₂.1.map (lineMap p q), hx₁₂.symm, hx₂₃⟩
  · exact Or.inr (Or.inl ⟨hmid₁.1.map (lineMap p q), hx₁₂, hx₁₃⟩)
  · exact Or.inr (Or.inr ⟨hmid₃.1.map (lineMap p q), hx₁₃.symm, hx₂₃.symm⟩)

/-- The line generated by two points of an affine subspace lies in that
subspace. -/
theorem line_pair_le_of_mem
    {p q x y : E} (hx : x ∈ line[ℝ, p, q]) (hy : y ∈ line[ℝ, p, q]) :
    line[ℝ, x, y] ≤ line[ℝ, p, q] :=
  affineSpan_le.2 (Set.pair_subset hx hy)

/-- Swap the first two petals of a three-sunflower. -/
theorem IsThreeSunflower.swap₁₂
    {U₁ U₂ U₃ : Set E} (h : IsThreeSunflower U₁ U₂ U₃) :
    IsThreeSunflower U₂ U₁ U₃ := by
  rcases h with ⟨h₁₂, h₁₃, h₂₃⟩
  exact ⟨(fun _ hx => h₁₂ ⟨hx.2, hx.1⟩), h₂₃, h₁₃⟩

/-- Swap the last two petals of a three-sunflower. -/
theorem IsThreeSunflower.swap₂₃
    {U₁ U₂ U₃ : Set E} (h : IsThreeSunflower U₁ U₂ U₃) :
    IsThreeSunflower U₁ U₃ U₂ := by
  rcases h with ⟨h₁₂, h₁₃, h₂₃⟩
  exact ⟨h₁₃, h₁₂, fun _ hx => h₂₃ ⟨hx.2, hx.1⟩⟩

/-- The full line-core theorem for an open convex three-sunflower.  No order or
pairwise-distinctness assumption is imposed on the three chosen hit points. -/
theorem openConvexThreeSunflower_everyLineMeetingThreeHitsCore
    {U₁ U₂ U₃ : Set E}
    (hU₁open : IsOpen U₁) (hU₂open : IsOpen U₂) (hU₃open : IsOpen U₃)
    (hU₁conv : Convex ℝ U₁) (hU₂conv : Convex ℝ U₂) (hU₃conv : Convex ℝ U₃)
    (hsun : IsThreeSunflower U₁ U₂ U₃)
    (hcore : ∃ c : E, InThreeCore U₁ U₂ U₃ c) :
    EveryLineMeetingThreeHitsCore U₁ U₂ U₃ := by
  intro p q hhit₁ hhit₂ hhit₃
  rcases hhit₁ with ⟨x₁, hx₁U₁, hx₁line⟩
  rcases hhit₂ with ⟨x₂, hx₂U₂, hx₂line⟩
  rcases hhit₃ with ⟨x₃, hx₃U₃, hx₃line⟩
  by_cases hx₁₂ : x₁ = x₂
  · subst x₂
    have hx₁U₃ : x₁ ∈ U₃ := hsun.1 ⟨hx₁U₁, hx₂U₂⟩
    exact ⟨x₁, ⟨hx₁U₁, hx₂U₂, hx₁U₃⟩, hx₁line⟩
  by_cases hx₁₃ : x₁ = x₃
  · subst x₃
    have hx₁U₂ : x₁ ∈ U₂ := hsun.2.1 ⟨hx₁U₁, hx₃U₃⟩
    exact ⟨x₁, ⟨hx₁U₁, hx₁U₂, hx₃U₃⟩, hx₁line⟩
  by_cases hx₂₃ : x₂ = x₃
  · subst x₃
    have hx₂U₁ : x₂ ∈ U₁ := hsun.2.2 ⟨hx₂U₂, hx₃U₃⟩
    exact ⟨x₂, ⟨hx₂U₁, hx₂U₂, hx₃U₃⟩, hx₂line⟩
  rcases three_distinct_points_on_line_one_strictly_between
      hx₁line hx₂line hx₃line hx₁₂ hx₁₃ hx₂₃ with hmid₂ | hmid₁ | hmid₃
  · obtain ⟨z, hzcore, hzline⟩ :=
      ordered_openConvexThreeSunflower_line_hitsCore
        hU₁open hU₂open hU₃open hU₁conv hU₂conv hU₃conv
        hsun hcore hx₁U₁ hx₂U₂ hx₃U₃ hmid₂
    exact ⟨z, hzcore, line_pair_le_of_mem hx₁line hx₃line hzline⟩
  · have hcore₂₁₃ : ∃ c : E, InThreeCore U₂ U₁ U₃ c := by
      rcases hcore with ⟨c, hc⟩
      exact ⟨c, hc.2.1, hc.1, hc.2.2⟩
    obtain ⟨z, hzcore, hzline⟩ :=
      ordered_openConvexThreeSunflower_line_hitsCore
        hU₂open hU₁open hU₃open hU₂conv hU₁conv hU₃conv
        hsun.swap₁₂ hcore₂₁₃ hx₂U₂ hx₁U₁ hx₃U₃ hmid₁
    exact ⟨z, ⟨hzcore.2.1, hzcore.1, hzcore.2.2⟩,
      line_pair_le_of_mem hx₂line hx₃line hzline⟩
  · have hcore₁₃₂ : ∃ c : E, InThreeCore U₁ U₃ U₂ c := by
      rcases hcore with ⟨c, hc⟩
      exact ⟨c, hc.1, hc.2.2, hc.2.1⟩
    obtain ⟨z, hzcore, hzline⟩ :=
      ordered_openConvexThreeSunflower_line_hitsCore
        hU₁open hU₃open hU₂open hU₁conv hU₃conv hU₂conv
        hsun.swap₂₃ hcore₁₃₂ hx₁U₁ hx₃U₃ hx₂U₂ hmid₃
    exact ⟨z, ⟨hzcore.1, hzcore.2.2, hzcore.2.1⟩,
      line_pair_le_of_mem hx₁line hx₂line hzline⟩

/-- The paper's sunflower segment lemma with the line-core theorem discharged
from open convexity. -/
theorem openConvexThreeSunflower_segment_forcing
    {U₁ U₂ U₃ : Set E}
    (hU₁open : IsOpen U₁) (hU₂open : IsOpen U₂) (hU₃open : IsOpen U₃)
    (hU₁conv : Convex ℝ U₁) (hU₂conv : Convex ℝ U₂) (hU₃conv : Convex ℝ U₃)
    (hsun : IsThreeSunflower U₁ U₂ U₃)
    (hcore : ∃ c : E, InThreeCore U₁ U₂ U₃ c)
    {p₁ p₂ p₃ : E}
    (hp₁ : p₁ ∈ U₁) (hp₂ : p₂ ∈ U₂) (hp₃ : p₃ ∈ U₃)
    (hp₃seg : p₃ ∈ segment ℝ p₁ p₂) :
    InThreeCore U₁ U₂ U₃ p₃ := by
  exact sunflower_segment_of_everyLineMeetingThreeHitsCore
    hU₁conv hU₂conv hsun
    (openConvexThreeSunflower_everyLineMeetingThreeHitsCore
      hU₁open hU₂open hU₃open hU₁conv hU₂conv hU₃conv hsun hcore)
    hp₁ hp₂ hp₃ hp₃seg

#print axioms real_three_distinct_one_strictly_between
#print axioms three_distinct_points_on_line_one_strictly_between
#print axioms line_pair_le_of_mem
#print axioms IsThreeSunflower.swap₁₂
#print axioms IsThreeSunflower.swap₂₃
#print axioms openConvexThreeSunflower_everyLineMeetingThreeHitsCore
#print axioms openConvexThreeSunflower_segment_forcing

end FanoLowerBound
