import FanoLowerBound.RatioCircuitCore
import FanoLowerBound.RadonNormalization
import FanoLowerBound.AffineBasisReduction
import FanoLowerBound.DirectFivePointRadon
import FanoLowerBound.RatioDistinctness
import FanoLowerBound.SixthCoordinates
import FanoLowerBound.SixPointRatioPairs
import FanoLowerBound.AllPositiveSixPointRadon
import FanoLowerBound.OnePositiveRebase
import FanoLowerBound.OnePositiveRebaseOther
import FanoLowerBound.DirectSixPointBranches
import FanoLowerBound.SixPointRadonComplete
import FanoLowerBound.SunflowerSegment

/-!
# Fano lower-bound Round 17

This kernel target retains the complete six-point strict `2--3` Radon lemma and
adds the order-convex sunflower segment deduction: the paper's Lemma 7 follows
from the line-core property isolated in its Lemma 6.
-/

#print axioms FanoLowerBound.ordered_ratio_circuit_core
#print axioms FanoLowerBound.ordered_ratio_circuit_strictRadon23
#print axioms FanoLowerBound.firstFourAffineBasis
#print axioms FanoLowerBound.fifth_coord_ne_zero
#print axioms FanoLowerBound.sixth_coord_ne_zero
#print axioms FanoLowerBound.sixth_over_fifth_coord_ne_zero
#print axioms FanoLowerBound.two_positive_direct_strictRadon23
#print axioms FanoLowerBound.three_positive_direct_strictRadon23
#print axioms FanoLowerBound.ratio01_ne_of_four_affineIndependent
#print axioms FanoLowerBound.sixPointRatio_injective
#print axioms FanoLowerBound.allPositive_sixPoint_strictRadon23
#print axioms FanoLowerBound.affineBasis_coord_eq_of_linearCombination
#print axioms FanoLowerBound.onePositive0_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.onePositive1_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.onePositive2_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.onePositive3_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive01_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive02_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive03_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive12_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive13_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive23_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.threePositiveNeg0_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.threePositiveNeg1_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.threePositiveNeg2_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.threePositiveNeg3_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.sixPoint_generalPosition_hasStrictRadon23
#print axioms FanoLowerBound.corePoint_on_segment_of_corePoint_on_line
#print axioms FanoLowerBound.sunflower_segment_of_corePoint_on_segment
#print axioms FanoLowerBound.sunflower_segment_of_line_hits_core
#print axioms FanoLowerBound.sunflower_segment_of_everyLineMeetingThreeHitsCore
