import FanoLowerBound.RatioCircuitCore
import FanoLowerBound.RadonNormalization
import FanoLowerBound.AffineBasisReduction
import FanoLowerBound.DirectFivePointRadon
import FanoLowerBound.RatioDistinctness
import FanoLowerBound.SixthCoordinates
import FanoLowerBound.SixPointRatioPairs
import FanoLowerBound.AllPositiveSixPointRadon
import FanoLowerBound.OnePositiveRebase
import FanoLowerBound.OnePositiveRebaseOther
import FanoLowerBound.DirectSixPointBranches
import FanoLowerBound.SixPointRadonComplete
import FanoLowerBound.SunflowerSegment
import FanoLowerBound.BoundaryExit
import FanoLowerBound.DoubleTriangle
import FanoLowerBound.ParallelCrossing
import FanoLowerBound.EndpointBranch
import FanoLowerBound.OrderedLineCore
import FanoLowerBound.GeneralLineCore
import FanoLowerBound.FanoForcingTable
import FanoLowerBound.FanoRadonForcing
import FanoLowerBound.FanoIndexNormalization
import FanoLowerBound.SixChosenFanoLines
import FanoLowerBound.GeneralPositionSelection

/-!
# Fano lower-bound Round 26

This kernel target retains the complete strict-Radon, sunflower, finite Fano-forcing,
index-normalization, and six-chosen-lines chain. It additionally selects representatives
from six nonempty open subsets of `ℝ³` so that every four are affinely independent.
-/

#print axioms FanoLowerBound.ordered_ratio_circuit_core
#print axioms FanoLowerBound.ordered_ratio_circuit_strictRadon23
#print axioms FanoLowerBound.firstFourAffineBasis
#print axioms FanoLowerBound.fifth_coord_ne_zero
#print axioms FanoLowerBound.sixth_coord_ne_zero
#print axioms FanoLowerBound.sixth_over_fifth_coord_ne_zero
#print axioms FanoLowerBound.two_positive_direct_strictRadon23
#print axioms FanoLowerBound.three_positive_direct_strictRadon23
#print axioms FanoLowerBound.ratio01_ne_of_four_affineIndependent
#print axioms FanoLowerBound.sixPointRatio_injective
#print axioms FanoLowerBound.allPositive_sixPoint_strictRadon23
#print axioms FanoLowerBound.affineBasis_coord_eq_of_linearCombination
#print axioms FanoLowerBound.onePositive0_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.onePositive1_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.onePositive2_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.onePositive3_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive01_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive02_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive03_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive12_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive13_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.twoPositive23_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.threePositiveNeg0_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.threePositiveNeg1_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.threePositiveNeg2_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.threePositiveNeg3_sixPoint_hasStrictRadon23
#print axioms FanoLowerBound.sixPoint_generalPosition_hasStrictRadon23
#print axioms FanoLowerBound.corePoint_on_segment_of_corePoint_on_line
#print axioms FanoLowerBound.sunflower_segment_of_corePoint_on_segment
#print axioms FanoLowerBound.sunflower_segment_of_line_hits_core
#print axioms FanoLowerBound.sunflower_segment_of_everyLineMeetingThreeHitsCore
#print axioms FanoLowerBound.exists_boundaryPoint_between_inside_outside
#print axioms FanoLowerBound.exists_lastOutsideParameter
#print axioms FanoLowerBound.sweptTriangleInterior_subset_of_openEdge
#print axioms FanoLowerBound.doubleSweptTriangleInterior_subset_petals
#print axioms FanoLowerBound.exists_boundaryPoint_with_doubleTriangleInclusions
#print axioms FanoLowerBound.strictTriangleCombination_mem_sweptTriangleInterior
#print axioms FanoLowerBound.base_endpoints_not_mem_edgeLine
#print axioms FanoLowerBound.parallel_crossing_of_lineMap_parameters
#print axioms FanoLowerBound.parallelLine_crosses_doubleSweptTriangles
#print axioms FanoLowerBound.weakBoundary_endpoint_or_strict
#print axioms FanoLowerBound.openSegment_subset_firstPetal_of_coreEdge
#print axioms FanoLowerBound.endpointBoundary_openSegment_hitsCore
#print axioms FanoLowerBound.endpointBoundary_baseLine_hitsCore
#print axioms FanoLowerBound.exists_small_symmetric_points_mem_open
#print axioms FanoLowerBound.ordered_openConvexThreeSunflower_line_hitsCore
#print axioms FanoLowerBound.real_three_distinct_one_strictly_between
#print axioms FanoLowerBound.three_distinct_points_on_line_one_strictly_between
#print axioms FanoLowerBound.line_pair_le_of_mem
#print axioms FanoLowerBound.IsThreeSunflower.swap₁₂
#print axioms FanoLowerBound.IsThreeSunflower.swap₂₃
#print axioms FanoLowerBound.openConvexThreeSunflower_everyLineMeetingThreeHitsCore
#print axioms FanoLowerBound.openConvexThreeSunflower_segment_forcing
#print axioms FanoLowerBound.fano_forcing_certificate_count
#print axioms FanoLowerBound.all_fano_forcing_certificates_valid
#print axioms FanoLowerBound.fano_forcing_table_complete
#print axioms FanoLowerBound.all_fano_forcing_certificates_geom_valid
#print axioms FanoLowerBound.FanoForcingCert.geomValid_of_mem
#print axioms FanoLowerBound.StrictRadon23.reorderRight
#print axioms FanoLowerBound.FanoForcingCert.forcesFivefold
#print axioms FanoLowerBound.all_fano_forcing_records_forceFivefold
#print axioms FanoLowerBound.every_fano_radon_config_forcesFivefold
#print axioms FanoLowerBound.every_fano_radon_config_contradicts_noFiveDistinctActive
#print axioms FanoLowerBound.StrictRadon23.reorderLeft
#print axioms FanoLowerBound.canonicalRadonConfig_mem_allRadonConfigs
#print axioms FanoLowerBound.canonicalized_orderedFive_hasCanonicalConfig
#print axioms FanoLowerBound.arbitraryOrderedFive_strictRadon_hasCanonicalConfig
#print axioms FanoLowerBound.arbitraryOrderedFive_strictRadon_contradicts_noFiveDistinctActive
#print axioms FanoLowerBound.sixChosenFanoLines_hasStrictRadon_contradiction
#print axioms FanoLowerBound.sixChosenFanoLines_generalPosition_contradiction
#print axioms FanoLowerBound.exists_mem_not_mem_proper_affineSubspace
#print axioms FanoLowerBound.exists_mem_avoid_affineSubspaces
#print axioms FanoLowerBound.every_fin4_emb_fin6_factors
#print axioms FanoLowerBound.exists_six_generalPosition_representatives
